### ISSUE TITLE
Why is the client able to run with out the server.

### ISSUE THREAD

**Issue by BellVirtual** [kstzl/UrsinaNetworking#2]
I was testing this library and I ran the server and had my friend connect to my server with his client using my servers ip address and the same port, and then I stopped running my server.
However his client was still running after I ended the server and could run without the server being up.

So why can the client run with out the server running and how do I tell if someone running a client on another network is connected to my server?

Also I was using the Minecraft example server and client for all of this.

**Comment by kstzl** [comment]
Hello, when the server is out, it will push to the client an "onConnectionError(Reason)" event. 
But without throwing any errors so its normal.

If you close your server, the client can not process with the server, logically.

**Comment by BellVirtual** [comment]
So the client can still launch without the server? And if its not connecting it will give me  the onConnectionError(Reason) error without crashing the client, is this correct.

**Comment by kstzl** [comment]
Networking and the game are "2 things different"
You can launch the game same if you're not connected but the client wont be able to spawn any cube (if i take the minecraft exemple) because its the server who "replicate" the cube
But you can check if the client is connected by just using the event "onConnectionEtablished", and yes, otherwise it will throw an "onConnectionError(Reason)" event, so you can make a little text in the game who show if you are connected or not ;)

![explanation](https://user-images.githubusercontent.com/78973002/114290405-d4675d00-9a7f-11eb-8e7e-eb6e7099d541.png)

Btw i added a little explanation how things works in UrsinaNetworking ^

**Comment by BellVirtual** [comment]
Oh ok cool thanks for explaining that too me, I have been developing with ursina for a little while but this is my first time trying to create a multiplayer game. Do you mind if I message you if I have any other questions about UrsinaNetworking?

**Comment by kstzl** [comment]
No problem haha and yes i'll be happy to answer your questions, so if you have it just contact me on discord ( K3#4869 ) its better ;)

**Comment by BellVirtual** [comment]
Ok sweet, will do.

**Comment by ghost** [comment]
You can make it close the game if the server is offline you know that right?
